apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-service.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "redis-service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "redis-service.selectorLabels" . | nindent 4 }}
