apiVersion: v2
name: store-stack
description: Complete store application stack (nginx, redis, httpbin)
type: application
version: 1.5.0
appVersion: "1.5"
maintainers:
  - name: POC Team

dependencies:
  - name: nginx-service
    version: 0.3.0
    repository: https://saurabh-newera.github.io/helm-charts
  
  - name: redis-service
    version: 0.3.0
    repository: https://saurabh-newera.github.io/helm-charts
  
  - name: httpbin-service
    version: 0.3.0
    repository: https://saurabh-newera.github.io/helm-charts
