apiVersion: v2
name: httpbin-service
description: A simple HTTP request/response testing service Helm chart for Fleet POC
type: application
version: 0.1.0
appVersion: "0.9.2"
maintainers:
  - name: POC Team
